feat: provision a server on hetzner

diff --git a/terraform/configuration/devops b/terraform/configuration/devops
--- a/terraform/configuration/devops
+++ b/terraform/configuration/devops
@@ -14,9 +14,29 @@ load_dotenv() {
   fi
 }
 
+docker() {
+    if command -v docker >/dev/null 2>&1; then
+        docker "$@"
+    elif command -v podman >/dev/null 2>&1; then
+        podman "$@"
+    else
+        echo "Error: Neither docker nor podman is installed" >&2
+        return 1
+    fi
+}
+
 download_all() {
+  git clone https://github.com/nillebco/rt-voice-assistant.git
+  pushd rt-voice-assistant
+  uv sync
+
+  if [ ! -d "models" ]; then
+    mkdir models
+  fi
+  # 25GiB
   curl -L -o models/mixtral-8x7b-instruct.Q4_K_M.gguf \
     https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
+  # 941MiB
   curl -L -o models/qwen2-1_5b-instruct.Q4_K_M.gguf \
     https://huggingface.co/Qwen/Qwen2-1.5B-Instruct-GGUF/resolve/main/qwen2-1_5b-instruct-q4_k_m.gguf
   docker pull ghcr.io/ggml-org/whisper.cpp:main
@@ -28,6 +48,7 @@ download_all() {
   curl -L https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin -o models/ggml-tiny.en.bin
   curl -L https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin -o models/ggml-base.en.bin
   curl -L https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin -o models/ggml-small.en.bin
+  popd
 }
 
 transcribe() {
@@ -36,6 +57,7 @@ transcribe() {
   model=${2:-$DEFAULT_WHISPER_MODEL}
   # one of main, main-cuda, main-musa, main-intel (defaults to main if not specified)
   tag=${3:-$DEFAULT_WHISPER_TAG}
+  pushd rt-voice-assistant
   if [ ! -d "audios" ]; then
     mkdir audios
   fi
@@ -49,10 +71,13 @@ transcribe() {
     -v audios:/audios \
     -v outputs:/outputs
     whisper.cpp:main "whisper-cli -m /models/ggml-${model}.bin -f $audio_file -ojf -of /outputs/out-$(basename $audio_file)"
+  popd
 }
 
 say() {
+  pushd rt-voice-assistant
   uv run -m rt_voice_assistant.say $@
+  popd
 }
 
 llm_up() {
@@ -71,13 +96,6 @@ llm_down() {
 case "$1" in
   "download")
     download_all
-    ;;
-  "install")
-    load_dotenv
-    tailscale up --authkey=${TAILSCALE_AUTH_KEY}
-    tailscale cert ${SERVICE_NAME}.${DOMAIN_NAME}
-    uv venv
-    uv pip install podman-compose
     ;;
   "llm-up")
     llm_up $2
